apiVersion: v1
kind: Secret
metadata:
  name: weather-service-secrets
type: Opaque
data:
  apikey: ${{FROM_GIT_API_KEY}}
  mongo-root-username: ${{FROM_GIT_MONGO_USER}}
  mongo-root-password: ${{FROM_GIT_MONGO_PASSWORD}}